# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Order

# Model Form Field configuration
form: $/lbaig/basket/models/order/fields.yaml

# Model Class name
modelClass: Lbaig\Basket\Models\Order

# Default redirect location
defaultRedirect: lbaig/basket/orders

# Create page
create:
    title: View Order
    redirect: lbaig/basket/orders/update/:id
    redirectClose: lbaig/basket/orders

# Update page
update:
    title: View Order
    redirect: lbaig/basket/orders
    redirectClose: lbaig/basket/orders

# Preview page
preview:
    title: Preview Order
